### ISSUE TITLE
你好，第一节课的回访好像b站没有更新

### ISSUE THREAD

**Issue by eatcosmos** [mindspore-courses/step_into_chatgpt#1]
https://space.bilibili.com/526894060/video

**Comment by lvyufeng** [comment]
剪辑中，我去催下

**Comment by xing-yiren** [comment]
课程回放已更新，久等啦：https://www.bilibili.com/video/BV16h4y1W7us/?spm_id_from=333.999.0.0
如果哪里内容缺失或者不连贯，也欢迎进行反馈~
